import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import "@rainbow-me/rainbowkit/styles.css";
import { CreditsProvider } from "./components/CreditsContext";

export const metadata = {
  title: "Tronique",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <CreditsProvider>{children}</CreditsProvider>
        </Providers>
      </body>
    </html>
  );
}
